accounts/urls.py
from django.urls import path
from allauth.account.views import LogoutView,SignupView
from .views import*
app_name='accounts'
urlpatterns = [
    path('logout/', LogoutView.as_view(), name='account_logout'),
    path('signup/',account_signup, name='account_signup'),
    path('login/',account_login , name='account_login'),
    path('change_email/', change_email, name='account_email'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset/done/',password_reset_done, name='password_reset_done'),
    path('change-password/',change_password, name='change_password'),
  
  
]



    

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("root.urls")),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path("courses/",include("courses.urls")),
    
   
]


urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path("", courses,name='courses'),
    path("category/<str:cat>",courses,name ="course_cat"),
    path("teacher/<str:teacher>",courses,name ="course_teacher"),
    path("search/",courses,name="course_teacher"),
    path("course_detail/<int:id>",course_detail,name="course_detail"),

]

root/urls.py
from django.urls import path
from .views import *

app_name = 'root'

urlpatterns = [
    path("",home,name="home"),# type: ignore
    path("about",about,name="about"),# type: ignore
    path("contact",contact,name="contact"), # type: ignore
    path("trainer",trainer,name="trainer")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block 'title' %}{% endblock 'title' %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css ' %}/animate.min.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css ' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css ' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css ' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Mentor
  * Updated: May 30 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center">
  
        <h1 class="logo me-auto" style='color:blue;font-family:B Titr;font-size:25;'><a href="{% url 'root:home' %}">آکادمی </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% url 'root:home' %}" class="logo me-auto"><img src="{% static 'assets/img/logo.png' %}" alt="" class="img-fluid"></a>-->
  
        
        
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="active" href="{% url 'root:home' %}">Home</a></li>
            <li><a href="{% url 'root:about' %}">About</a></li>
            <li><a href="{% url 'courses:courses' %}">Courses</a></li>
            <li><a href="{% url 'root:trainer' %}">Trainers</a></li>
            <li><a href="{% url 'root:contact' %}">Contact</a></li>
            <li class="dropdown"><a href="#"><span>Category</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                {% for cat in category %}
                <li><a href={% url 'courses:course_cat' cat=cat.name %}>{{cat.name}}</a></li>
                {% endfor %}

              </ul>
            </li>
            
            {% if request.user.is_authenticated %}
            <li>ٌWelcome {{request.user.username}}</li>
            <li><img src={{request.user.image.url}}></li>
            <li><a href={% url 'accounts:account_logout' %}>Logout</a></li>
            {% else %}
            <li><a href={% url 'accounts:account_login' %}>Login</a></li>
            <li><a href={% url 'accounts:account_signup' %}>signup</a></li>
            {% endif %}
                
            
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
  
      </div>
    </header><!-- End Header -->

    {% block 'content'  %}

    {% endblock 'content' %}













  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Mentor</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>

            {% if messages %}
              {% for message in messages %}
                <p style='color:green'>{{ message}}</p>
              {% endfor %}
            {% endif %}
            <form  method="post">
              {% csrf_token %}
              <input type="email" name="email">
              <input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Mentor</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js ' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js ' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js ' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js ' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js ' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js ' %}"></script>

</body>

</html>