config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("root.urls")),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path("courses/",include("courses.urls")),
    
   
]


urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path("", courses,name='courses'),
    path("category/<str:cat>",courses,name ="course_cat"),
    path("teacher/<str:teacher>",courses,name ="course_teacher"),
    path("search/",courses,name="course_teacher"),
    path("course_detail/<int:id>",course_detail,name="course_detail"),

]

root/urls.py
from django.urls import path
from .views import *

app_name = 'root'

urlpatterns = [
    path("",home,name="home"),# type: ignore
    path("about",about,name="about"),# type: ignore
    path("contact",contact,name="contact"), # type: ignore
    path("trainer",trainer,name="trainer")
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime





class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Skills(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name



class Trainer(models.Model):
    info = models.ForeignKey(User , on_delete=models.CASCADE)
    skills = models.ManyToManyField(Skills)
    description = models.TextField()
    image = models.ImageField(upload_to='trainer', default='tr.png')
    twitter = models.CharField(max_length=255, default='#')
    facebook = models.CharField(max_length=255, default='#')
    instagram = models.CharField(max_length=255, default='#')
    linkdin = models.CharField(max_length=255, default='#')
    status = models.BooleanField(default=False)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.info.username
    
    



class Course(models.Model):
    image = models.ImageField(upload_to='course',default='defualt2.jpg')
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=100)
    content = models.TextField()
    price = models.IntegerField(default=0)
    teacher = models.ForeignKey(Trainer,on_delete=models.CASCADE)
    counted_views = models.IntegerField(default=0)
    counted_like = models.IntegerField(default=0)
    available_seat = models.IntegerField(default=0)
    schedule = models.DateTimeField(default=datetime.datetime.now())
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return self.title
    
    def capt(self):
        return self.title.capitalize()
 

courses/views.py
from django.core.paginator import Paginator
from django.shortcuts import render , get_object_or_404
from .models import Course
from courses.models import Category
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage

def courses(request, cat=None, teacher=None):
    category = Category.objects.all()
    
    if cat:
        course= Course.objects.filter(category__name=cat)
    elif teacher:
        course = Course.objects.filter(teacher__info__username=teacher)
    elif request.GET.get('search'):
        course= Course.objects.filter(content__contains=request.GET.get('search'))
    else:
        course= Course.objects.filter(status=True)


    course = Paginator(course, 2)     
    first_page= 1
    last_page = course.num_pages
    try:
         page_number = request.GET.get('page')
         course = course.get_page(page_number)
    
    except EmptyPage:
        course = course.get_page(1)
    except PageNotAnInteger:
        course = course.get_page(1)

    context = {
        "courses": course,
        'category': category,
        "last_page": last_page,
        "first_page": first_page,
    }
    return render(request, 'courses/course.html', context=context)

             
def course_detail(request, id):
    try:
        course = Course.objects.get(id=id)
        id_list = []
        courses = Course.objects.filter(status=True)
        for cr in courses:
            id_list.append(cr.id)

        id_list.reverse()
        
        if id_list[0] == id :
            next_course = Course.objects.get(id = id_list[1])
            previous_course = None

        elif id_list[-1] == id :
            next_course = None
            previous_course = Course.objects.get(id = id_list[-2])

        else:
            next_course = Course.objects.get(id=id_list[id_list.index(id)+1])
            previous_course = Course.objects.get(id=id_list[id_list.index(id)-1])


        course.counted_views += 1
        course.save()
        context ={"course": course,
                  'next_course': next_course,
                  'previous_course': previous_course,
        }
        return render(request,'courses/course-details.html',context=context)
    except:
        return render(request,'courses/404.html')

templates/courses/course-details.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}course{% endblock 'title' %}
{% block 'content' %}

  <main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Course Details</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->
    <!-- ======= Cource Details Section ======= -->
    <section id="course-details" class="course-details">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-8">
            <img src={{course.image.url}} class="img-fluid" alt="">
            <h3>{{course.title}}</h3>
            <p>
              {{course.content}}
            </p><br>
            <div class="navigation-area">
              <div class="row">
                {% if next_course and previous_course %}
                <div class="col-lg-5 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' id=previous_course.id %}><img class="img-fluid" src={{previous_course.image.url}} width="170px" height="180px" alt=""></a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' id=previous_course.id %}><span class="lnr text-white lnr-arrow-left"></span></a>
                  </div>
                  <div class="detials">
                    <p> &nbsp;&nbsp; Prev Course</p>
                    <a href={% url 'courses:course_detail' id=previous_course.id %}>
                      <h4>&nbsp;&nbsp; {{previous_course.title}}</h4>
                    </a>
                  </div>
                </div>
                <div class="col-lg-5 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                  <div class="detials">
                    <p>Next course &nbsp;&nbsp; </p>
                    <a href={% url 'courses:course_detail' id=next_course.id %}>
                      <h4>{{next_course.title}}</h4>
                    </a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' id=next_course.id %}><span class="lnr text-white lnr-arrow-right"></span></a>
                  </div>
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' id=next_course.id %}><img class="img-fluid" src={{next_course.image.url}} width="170px" height="180px" alt=""></a>
                  </div>
                </div>
                {% elif next_course %}
                <div class="col-lg-5 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                  <div class="detials">
                    <p>Next course &nbsp;&nbsp;</p>
                    <a href={% url 'courses:course_detail' id=next_course.id %}>
                      <h4>{{next_course.title}}</h4>
                    </a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' id=next_course.id %}><span class="lnr text-white lnr-arrow-right"></span></a>
                  </div>
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' id=next_course.id %}><img class="img-fluid" src={{next_course.image.url}} width="170px" height="180px" alt=""></a>
                  </div>
                </div>
                {% else %}
                <div class="col-lg-5 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' id=previous_course.id %}><img class="img-fluid" src={{previous_course.image.url}} width="170px" height="180px" alt=""></a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' id=previous_course.id %}><span class="lnr text-white lnr-arrow-left"></span></a>
                  </div>
                  <div class="detials">
                    <p> &nbsp;&nbsp; Prev Course</p>
                    <a href={% url 'courses:course_detail' id=previous_course.id %}>
                      <h4>&nbsp;&nbsp; {{previous_course.title}}</h4>
                    </a>
                  </div>
                </div>
                {% endif %}
              </div>
            </div><br>
            <div class="comments-area">
              <h4>05 Comments</h4>
              <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c1.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">Emilly Blunt</a></h5>
                      <p class="date">December 4, 2017 at 3:12 pm </p>
                      <p class="comment">
                        Never say goodbye till the end comes!
                      </p>
                    </div>
                  </div>
                  <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                  </div>
                </div>
              </div>
              <div class="comment-list left-padding">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c2.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">Elsie Cunningham</a></h5>
                      <p class="date">December 4, 2017 at 3:12 pm </p>
                      <p class="comment">
                        Never say goodbye till the end comes!
                      </p>
                    </div>
                  </div>
                  <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                  </div>
                </div>
              </div>
              <div class="comment-list left-padding">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c3.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">Annie Stephens</a></h5>
                      <p class="date">December 4, 2017 at 3:12 pm </p>
                      <p class="comment">
                        Never say goodbye till the end comes!
                      </p>
                    </div>
                  </div>
                  <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                  </div>
                </div>
              </div>
              <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c4.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">Maria Luna</a></h5>
                      <p class="date">December 4, 2017 at 3:12 pm </p>
                      <p class="comment">
                        Never say goodbye till the end comes!
                      </p>
                    </div>
                  </div>
                  <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                  </div>
                </div>
              </div>
              <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c5.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">Ina Hayes</a></h5>
                      <p class="date">December 4, 2017 at 3:12 pm </p>
                      <p class="comment">
                        Never say goodbye till the end comes!
                      </p>
                    </div>
                  </div>
                  <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                  </div>
                </div>
              </div>
            </div><br>
            <div class="comment-form" >
              <h4 align='center'>Leave a Comment</h4>
              <form>
                <div class="form-group form-inline">
                  <div class="form-group col-lg-6 col-md-12 name">
                    <input type="text" class="form-control" id="name" placeholder="Enter Name"
                      onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                  </div>
                  <div class="form-group col-lg-6 col-md-12 email">
                    <input type="email" class="form-control" id="email" placeholder="Enter email address"
                      onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" id="subject" placeholder="Subject"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
                </div>
                <div class="form-group">
                  <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
                </div>
                <a href="#" class="primary-btn text-uppercase">Post Comment</a>
              </form>
            </div>
          </div>
          <div class="col-lg-4">

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Trainer</h5>
              <p><a href="#">{{course.teacher.info.username}}</a></p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Course Fee</h5>
              <p>{{course.price}}$</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Available Seats</h5>
              <p>{{course.available_seat}}</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Schedule</h5>
              <p>{{course.schedule|date:"D d M Y----H:i A"}}</p>
            </div>

          </div>
        </div>
      </div>
    </section><!-- End Cource Details Section -->

  </main><!-- End #main -->

 {% endblock 'content' %}

templates/courses/course.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}course{% endblock 'title' %}
{% block 'content' %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Courses</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs --><br>
    <div class="single-sidebar-widget search-widget" align="center">
      <form class="search-form" action="#">
          <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
          <button type="submit">click</button>
      </form>
    </div>

    <!-- ======= Courses Section ======= -->
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% for cr in courses %}

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">
              <img src={{cr.image.url}} class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  {% for cat in cr.category.all  %}
                  <h4>{{cat.name}}</h4>
                  {% endfor %}
                  <p class="price">${{cr.price}}</p>
                </div>

                <h3><a href="{% url 'courses:course_detail' id=cr.id %}">{{cr.capt}}</a></h3>
                <p>{{cr.content|truncatechars:10}}</p>
                <div class="trainer d-flex justify-content-between align-items-center">
                  <div class="trainer-profile d-flex align-items-center">
                    <img src={{cr.teacher.image.url}} class="img-fluid" alt="">
                    <span><a href= {% url 'courses:course_teacher' teacher=cr.teacher.info.username %}> {{cr.teacher.info.username}}</a></span>
                  </div>
                  <div class="trainer-rank d-flex align-items-center">
                    <i class="bx bx-user"></i>&nbsp;{{cr.counted_views}}
                    &nbsp;&nbsp;
                    <i class="bx bx-heart"></i>&nbsp;{{cr.counted_like}}
                    <span>{{cr.schedule|date:'Y/ m/ d'}}</span>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- End Course Item-->
          {% endfor %}
       

        </div>

      </div>
    </section><!-- End Courses Section -->
    <div align="center" style="font-size:35px;">
      {% if courses.has_next and courses.has_previous %}
      <a href="?page={{first_page}}"><<</a>
      <a href="?page={{courses.previous_page_number}}">{{courses.previous_page_number}}</a>
      <a href="?page={{courses.previous_page_number}}"><  </a>
      <a href="?page={{ courses.number }}">{{ courses.number }}</a>
      <a href="?page={{courses.next_page_number}}">></a>
      <a href="?page={{courses.next_page_number}}">{{courses.next_page_number}}</a>
      <a href="?page={{last_page}}">>></a>
      {% elif courses.has_next %}
      <a href="?page={{courses.next_page_number}}">></a>
      <a href="?page={{courses.next_page_number}}">{{courses.next_page_number}}</a>
      <a href="?page={{last_page}}">>></a>
      {% elif courses.has_previous%}
      <a href="?page={{first_page}}"><<</a>
      <a href="?page={{courses.previous_page_number}}">{{courses.previous_page_number}}</a>
      <a href="?page={{courses.previous_page_number}}"><  </a>
    </div>
      {% endif %}
  </main><!-- End #main -->
  {% endblock 'content' %}